export const USER_ROLES = {
  GUEST: 'GUEST',
  HOST: 'HOST',
  PROPERTY_MANAGER: 'PROPERTY_MANAGER',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const PROPERTY_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};